Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.box_version = "2011.0"

  config.vm.define "server" do |server|
    server.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    
  end

end
