IP_SERVER="192.168.42.110"

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.box_version = "2011.0"
  # config.vagrant.plugins = ["vagrant-vbguest"]

  config.vm.provider "virtualbox" do |v|
    v.cpus = 1
    v.memory = 1024
  end

  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: IP_SERVER
    # server.trigger.before :
    server.vm.provision "shell",  path: "scripts/install_k3s.sh",
      env: {"NODE_IP" => IP_SERVER}
    server.vm.synced_folder "./config", "/tt", type: "virtualbox"
    # config.vm.provision :reload

  end

end
