Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.box_version = "2011.0"

  config.vm.provider "virtualbox" do |vb|
  end

  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    # master.vm.network "private_network", ip: "192.168.42.110/25"
    master.vm.network "private_network", ip: "192.168.56.110/25"
    master.vm.provision "shell",  path: "scripts/install_k3s.sh"

    
  end

  config.vm.define "worker" do |worker|
    worker.vm.hostname = "worker"
    # worker.vm.network "private_network", ip: "192.168.42.111/25"
    worker.vm.network "private_network", ip: "192.168.56.111/25"
    worker.vm.provision "shell",  path: "scripts/install_k3s.sh"

  end


end
