Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.box_version = "2011.0"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 1024
  end
  
  config.vm.provision "shell",  path: "scripts/install_k3s.sh"
  
  config.vm.define "master", primary: true do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.42.110"
    master.vm.provision "shell",  inline:  <<-EOF
      echo 'Master Script...'
      set -ex
      echo '192.168.42.111 worker' >> /etc/hosts

      echo "Installing master k3S..."
      # curl -sfL https://get.k3s.io | sh -
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--flannel-backend=none --disable-network-policy --cluster-cidr=192.168.0.0/16" sh -

      echo "k3S master node installed."
      
      EOF
      
    end
    
  config.vm.define "worker" do |worker|
      worker.vm.hostname = "worker"
      worker.vm.network "private_network", ip: "192.168.42.111"
      worker.vm.provision "shell",  inline:  <<-EOF
      echo 'Worker Script...'
      set -ex
      echo '192.168.42.110 master' >> /etc/hosts

      echo "Installing worker k3S..."
      curl -sfL https://get.k3s.io | K3S_URL=https://master:6443 K3S_TOKEN=mytoken sh -
      echo "k3S worker node installed."


    EOF
    
  end


end
